### ISSUE TITLE
Linux system call census

### ISSUE THREAD

**Issue by acw** [GaloisInc/HaLVM#117]
MUSL defines ~200 system calls that it may invoke. We need to do a census, to determine which of those calls we are or are not going to implement, which can be shared across HaLVM backends, which need to be backend-specific, which are going to potentially kick out to user-defined backends, etc.

This initial census is being performed in zHALVMCore/musl_syscall_table.txt`.

**Comment by mbj** [comment]
@acw The `.txt` file is not associated with an URl. Maybe a markdown / edit mishap.

**Comment by acw** [comment]
Initial version complete in f9bd1c6.
