### ISSUE TITLE
repos.halvm.org appears to be down

### ISSUE THREAD

**Issue by henrytill** [GaloisInc/HaLVM#123]
I am attempting to set up an environment following the instructions in [HACKING.md](https://github.com/GaloisInc/HaLVM/blob/master/HACKING.md), using Fedora Server 26 in VirtualBox 5.2.0.

I have reached step 3, but `repos.halvm.org` seems to be down:
```
[ht@localhost ~]$ sudo dnf install http://repos.halvm.org/fedora-26/x86_64/halvm-yum-repo-26-3.fc26.noarch.rpm
[sudo] password for ht: 
Fedora 26 - x86_64 - Updates                                                                          15 MB/s |  16 MB     00:01    
Fedora 26 - x86_64                                                                                   7.8 MB/s |  53 MB     00:06    
Last metadata expiration check: 0:00:04 ago on Sat 28 Oct 2017 09:54:00 AM EDT.
[MIRROR] halvm-yum-repo-26-3.fc26.noarch.rpm: Curl error (28): Timeout was reached for http://repos.halvm.org/fedora-26/x86_64/halvm-yum-repo-26-3.fc26.noarch.rpm [Connection timed out after 120002 milliseconds]
[FAILED] halvm-yum-repo-26-3.fc26.noarch.rpm: Curl error (28): Timeout was reached for http://repos.halvm.org/fedora-26/x86_64/halvm-yum-repo-26-3.fc26.noarch.rpm [Connection timed out after 120002 milliseconds]
Curl error (28): Timeout was reached for http://repos.halvm.org/fedora-26/x86_64/halvm-yum-repo-26-3.fc26.noarch.rpm [Connection timed out after 120002 milliseconds]
```

Other network operations are working fine inside the VM, and attempting to ping `repos.halvm.org` from both inside and outside the VM gives no response.

**Comment by TomMD** [comment]
Our server room has been having heat issues, resulting in some non-essential services being turned off.  I'm not positive, but if halvm.org was hosted internally then this is likely the issue.

**Comment by acw** [comment]
Looks like everything should be back up. As a positive side effect of our AC blowout, your issue prompted me to update my "even-numbered Fedora" build servers from 24 to 26. So there should be new, shiny Fedora 26 RPMs ready to go. I will warn you, however, that I have only built them, not tested them. The "Should Just Word" (tm, famous last work, etc.), though.

**Comment by henrytill** [comment]
@acw: thanks!  I will give the new 26 RPMs a test and see how they go.

I did create a VM with the "stock" Xen and succeeded in running several of the examples.  There were a few little configuration bits I had to do to get Xen to behave nicely (for example, getting `xenconsoled.service` to launch and connect to `xenstored` required me to relax the SELinux policy on Fedora 26 to "permissive").  

Do you think writing these things down somewhere in/around this repo is the kind of thing that would be helpful for prospective HaLVM users/contributors?

**Comment by acw** [comment]
Absolutely! Indeed, if you'd be interested, updating HACKING.md in any places you think would be helpful would be great.

I'm going to close this ticket, since repos.halvm.org seems to be working, but feel free to open a new one with any other issues you find.
