### ISSUE TITLE
Build failure on Fedora Server 26

### ISSUE THREAD

**Issue by aierl** [GaloisInc/HaLVM#125]
I was following the steps as per https://github.com/GaloisInc/HaLVM/blob/master/HACKING.md
(i have cloned the master branch)
There was no issue till step 5 configuration

```bash
$ git clone https://github.com/GaloisInc/HaLVM
$ git submodule update --init --recursive
$ autoconf
$ ./configure --enable-gmp
```

at this step the build fails with  
```
 ERROR: Couldn't find required version of Alex
  ERROR: Couldn't find required version of Cabal
  ERROR: Couldn't find required version of Happy
```
the following version of  alex , happy were installed  when performing the step
```
sudo dnf install ghc cabal-install alex happy hscolour

Package ghc-8.0.2-57.fc26.x86_64 is already installed, skipping.
Package cabal-install-1.24.0.2-3.fc26.x86_64 is already installed, skipping.
Package alex-3.2.1-1.fc26.x86_64 is already installed, skipping.
Package happy-1.19.5-8.fc26.x86_64 is already installed, skipping.
Package hscolour-1.24.1-2.fc26.x86_64 is already installed, skipping.
Dependencies resolved.
Nothing to do.
Complete!
```
when trying to fetch the version manually

/usr/bin/happy: error while loading shared libraries: libHSmtl-2.2.1-BLKBelFsPB3BoFeSWSOYj6-ghc8.0.2.so: cannot open shared object file: No such file or directory

/usr/bin/alex: error while loading shared libraries: libHSrandom-1.1-9tceXaeYIMZ4JrKq20Egog-ghc8.0.2.so: cannot open shared object file: No such file or directory

/usr/bin/cabal: error while loading shared libraries: libHSrandom-1.1-9tceXaeYIMZ4JrKq20Egog-ghc8.0.2.so: cannot open shared object file: No such file or directory

side note: Also the link to mailing list mentioned in the Hacking.md is not working

**Comment by acw** [comment]
It sounds like something's odd with your GHC insulation. I can't repeat this under Fedora 26 on Docker.  I'll try to get Fedora Server running in a VM and see if I can replicate it.

Also, which link is broken? I must be going blind, because I don't see a link in HACKING.md that points to a mailing list.

**Comment by aierl** [comment]
Thanks for the reply, I will try with different fedora server on vm and 
would let you know.
The HaLVM mailing list link on the github README. MD 4. How to contact 
us pointed to community. Galois. Com /mailman /listinfo/halvm-devel is 
not reachable.
Also I would like to thank contributors for the efforts for HaLVM.

**Comment by acw** [comment]
Ah, right. I've updated the README to reflect our move to [devel.unikernel.org](https://devel.unikernel.org).

**Comment by acw** [comment]
So, it wasn't just you. It turns out that the Haskell packages for Fedora 26 are missing a bunch of dependency information. If you run the following command:

```
sudo dnf install ghc-random-devel ghc-mtl-devel ghc-zlib-devel ghc-tar-devel ghc-ed25519-devel ghc-base64-bytestring-devel ghc-cryptohash-sha256-devel ghc-base16-bytestring-devel ghc-stm-devel ghc-text-devel ghc-network-devel
```

It should clear everything up for you. Give it a try, and tell me if it works. I've updated `HACKING.md` to match.

**Comment by aierl** [comment]
it works like a charm. Thanks a lot :)
