### ISSUE TITLE
halvm-cabal should force -j1

### ISSUE THREAD

**Issue by acw** [GaloisInc/HaLVM#36]
Experiments suggest that the weird Cabal version problems we're seeing on Arch and other systems is due to parallel builds; when Cabal wants to do a parallel build, it forces compilation of Setup.hs, regardless of the build-type.

We should modify halvm-cabal to force -j1 to make this problem go away.

**Comment by thumphries** [comment]
Is this still desirable? Three-char patches are my specialty.

**Comment by acw** [comment]
Looks like this got fixed, possibly by Tim?
