### ISSUE TITLE
Cabal build error

### ISSUE THREAD

**Issue by smilliken** [GaloisInc/HaLVM#37]
I'm getting an error while running make:

```
$ make
<snip>
In-place registering Cabal-1.20.0.0...
Installing library in
$HOME/projects/HaLVM/platform_ghc/lib/x86_64-linux-ghc-7.8.4/Cabal-1.20.0.0
Registering Cabal-1.20.0.0...
Setup: Cabal-1.20.0.0: Warning: haddock-interfaces:
$HOME/projects/HaLVM/platform_ghc/share/doc/x86_64-linux-ghc-7.8.4/Cabal-1.20.0.0/html/Cabal.haddock
doesn't exist or isn't a file
Cabal-1.20.0.0: Warning: haddock-html:
$HOME/projects/HaLVM/platform_ghc/share/doc/x86_64-linux-ghc-7.8.4/Cabal-1.20.0.0/html
doesn't exist or isn't a directory
ghc-pkg: $HOME/.ghc/x86_64-linux-7.8.4/package.conf.d: createDirectory:
does not exist (No such file or directory)

Error during cabal-install bootstrap:
Installing the Cabal package failed.
make: *** [$HOME/projects/HaLVM/platform_ghc/bin/cabal] Error 2
```

System:
```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.1 LTS
Release:        14.04
Codename:       trusty

$ uname -a
Linux 3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```

I believe this relates to https://github.com/haskell/cabal/issues/1790, but haven't figured out where to apply the `--no-doc` flag mentioned by YoEight.

**Comment by acw** [comment]
Thanks for the bug report. Unfortunately I don't have a Ubuntu 14.04.1 VM handy right at the moment, but I'll work one up and try to replicate it there.

As a work around, you can try running configure with --disable-docs and see if this lets the build go through. This is not ideal, as you won't get Haddock'd docs of the various HaLVM libraries, but it might be enough to get you started.

**Comment by acw** [comment]
Hmmmm!

I'm having trouble replicating this error. Out of curious, did you have GHC / Haddock / Cabal installed before you started building the HaLVM? What versions were those?

**Comment by dysinger** [comment]
if you have docker you can close this ticket by proving to yourself that a base ubuntu:14.04 docker image can be built up to HaLVM master HEAD

```
cat >Dockerfile <<\EOF
FROM ubuntu:14.04
RUN apt-get update
RUN apt-get install -y \
    autoconf \
    automake \
    build-essential \
    curl \
    git \
    libgmp-dev \
    libncurses5-dev \
    libtool \
    libxen-dev \
    xen-hypervisor \
    zlib1g-dev
RUN git clone --recursive https://github.com/GaloisInc/HaLVM.git /usr/src
WORKDIR /usr/src
RUN autoconf
RUN ./configure
RUN make
RUN make install
EOF

docker build -t ubuntu:14.04-halvm .
```

the end result for me is .... success!

```
Successfully built dc9d342c35ff
```

This issue can be closed
