### ISSUE TITLE
Generated scripts assume /bin/sh has features ubuntu /bin/sh does not have

### ISSUE THREAD

**Issue by AFDudley** [GaloisInc/HaLVM#38]
Ubuntu links /bin/dash to /bin/sh by default.
This is the workaround that worked for me, feel free to change the shell scripts or whatever:
`# rm /bin/sh`
`# ln -s /bin/bash /bin/sh`

**Comment by thumphries** [comment]
Thanks for noticing this. We've done very little testing on non-Fedora systems, so your time is much appreciated.

I ran `checkbashisms` and it found a small problem with string concatenation. Hopefully that's all.
If this is still a problem, try swapping `#/bin/sh` for `$/bin/bash` in `halvm-cabal` and `halvm-config`.

**Comment by AFDudley** [comment]
Cool, I will check this out again at some point.
