### ISSUE TITLE
Respond to PV shutdown / restart

### ISSUE THREAD

**Issue by thumphries** [GaloisInc/HaLVM#46]
Relying on `xl destroy` to close out a domain causes problems

**Comment by acw** [comment]
Specifically, there's a clean shutdown VIRQ somewhere, I believe, and the HaLVM should probably do something sensible with it.

**Comment by thumphries** [comment]
I have been informed ACPI for a PV domain is apparently not a thing.

PV shutdown seems to be implemented via a XenStore watch, e.g. `xl shutdown 10` just creates `/local/domain/10/control/shutdown = "poweroff"`. This is easy enough to implement in `HALVMCore`, so I'll add a user-exposed facility there.

Is it a good idea to handle this by default? Is the HaLVM supposed to work without a `xenstored`?
