### ISSUE TITLE
`xsGetPermissions` would throw error

### ISSUE THREAD

**Issue by izgzhen** [GaloisInc/HaLVM#52]
When I use the function like this:

```
perms <- xsGetPermissions xs here
writeConsole con $ "Permissions " ++ show perms
```

A mysterious error would jump out:
```
libxl: error: libxl_dom.c:35:libxl__domain_type: unable to get domain type for domid=16
Unable to attach console
libxl: error: libxl_exec.c:118:libxl_report_child_exitstatus: console child [0] exited with error status 1
```

**Comment by izgzhen** [comment]
`xsSetPermission`, `xsMakeDirectory` throws as well

**Comment by thumphries** [comment]
These look like legitimate permissions errors. In order to run `xsGetPermissions` the domain must be given additional privileges, see #47.

`xsMakeDirectory` will throw if the domain does not have permission to write at that path, and also if the path syntax is incorrect. I think a trailing "/" will cause a syntax error. Use `xenstore-ls -p` to view XenStore permissions.

Likewise, for `xsSetPermissions`, we need to have write access to the target path.

Could you post your usage of `xsMakeDirectory`?

**Comment by izgzhen** [comment]
```
main :: IO ()
main = do
  con <- initXenConsole
  xs  <- initXenStore
  let console s = writeConsole con $ s ++ "\n"

  me <- xsGetDomId xs
  console $ "Got ID = " ++ show me
  here <- xsGetDomainPath xs me
  console $ "Here " ++ show here

  keys <- listKeys xs "/rendezvous"
  console $ "Keys " ++ show keys

  values <- listValues xs here keys
  console $ "Values " ++ show values

--  xsWrite xs ("/transport" </> show me) $ show me                                                                            

--  perms <- xsGetPermissions xs "/transport" -- This would cause error                                                        
--  console $ "Permissions " ++ show perms                                                                                     

--  xsMakeDirectory xs $ here </> "new" -- will cause same error as above                                                        
--  console "Made new directory"

--  xsSetPermissions xs (here) [ReadWritePerm me] -- same as above                                                             

  threadDelay (2 * 1000 * 1000)

listKeys :: XenStore -> FilePath -> IO [FilePath]
listKeys xs here = filter (/= "") `fmap` xsDirectory xs here

getValue :: XenStore -> FilePath -> IO String
getValue xs key = handle handleException (emptify `fmap` xsRead xs key)
  where
   handleException :: ErrorCode -> IO String
   handleException _ = return "<read error>"
   emptify "" = "<empty>"
   emptify s  = s

listValues xs here keys = mapM (getValue xs) (map (here </>) keys)
```

**Comment by thumphries** [comment]
Looks like correct usage. We should compare against output of `xenstore-ls -p` before blaming HALVMCore.

Does transport exist and have permissions "bX" in `xenstore-ls -p`?
Does the domain in question have write access to `here`?

**Comment by izgzhen** [comment]
First, my `xenstore-ls` is a little strange. when I `xenstore-ls "/transport"`, it doesn't report warning so the directory exists. But when I  `xenstore-ls -p "/transport"`, nothing appears as well.

As a comparison, `xenstore-ls -p "/local"` will show:
```
domain = ""  . . . . . . . . . . . . . . . . . . . . . . . .  (n0)
 0 = ""  . . . . . . . . . . . . . . . . . . . . . . . . . .  (n0)
  name = "Domain-0"  . . . . . . . . . . . . . . . . . . . .  (n0)
  memory = ""  . . . . . . . . . . . . . . . . . . . . . . .  (n0)
   target = "3939384"  . . . . . . . . . . . . . . . . . . .  (n0)
   static-max = "4294967292" . . . . . . . . . . . . . . . .  (n0)
   freemem-slack = "183664"  . . . . . . . . . . . . . . . .  (n0)
  libxl = "" . . . . . . . . . . . . . . . . . . . . . . . .  (n0)
   disable_udev = "1"  . . . . . . . . . . . . . . . . . . .  (n0)
```

Second, the domain is unprivileged, so although `here` is `/local/domain/XX` in which it has read permissions, but it doesn't have write permission as I found.

**Comment by thumphries** [comment]
Yeah, enumerating all the domains without their participation is probably not possible with an ordinary domU.

If you control all the domains, you could coordinate by having them write their domains into a shared folder, similar to the way `Rendezvous` works. But, if you don't control them, you'll need to privilege the domU. This probably means fixing #47 first.

I suspect `/transport` doesn't exist, and `getPermissions` is throwing `ENOENT` or similar.

**Comment by izgzhen** [comment]
OK, I got it. Although I am now trying to bypass this problem by trying another way of programming, but it seems worth to fix the permission and privilege problems, if we'd like see some more dynamic configuration of domains.

**Comment by thumphries** [comment]
Agreed.
