### ISSUE TITLE
happy-1.19.5 does not compile

### ISSUE THREAD

**Issue by gracjan** [GaloisInc/HaLVM#54]
Compilation of a bundled happy-1.19.5 fails with:

```
templates/GenericTemplate.hs:104:22:
    Couldn't match expected type ‘Bool’
                with actual type ‘Happy_GHC_Exts.Int#’
    In the expression:
      (n Happy_GHC_Exts.<# (0# :: Happy_GHC_Exts.Int#))
    In a stmt of a pattern guard for
                   a case alternative:
      (n Happy_GHC_Exts.<# (0# :: Happy_GHC_Exts.Int#))
    In a case alternative:
        n | (n Happy_GHC_Exts.<# (0# :: Happy_GHC_Exts.Int#))
          -> (happyReduceArr Happy_Data_Array.! rule) i tk st
          where
              rule
                = (Happy_GHC_Exts.I#
                     ((Happy_GHC_Exts.negateInt#
                         ((n Happy_GHC_Exts.+# (1# :: Happy_GHC_Exts.Int#))))))
Failed to install happy-1.19.5
```

Note:
- I do not have system-wide `ghc` installed, it is using the one that downloads when `make` runs
- I had to install system-wide `happy` (version `1.18.9`). it enabled the build as per #53, but otherwise seems unused.

**Comment by gracjan** [comment]
This works:

```
PATH=/vagrant/HaLVM/platform_ghc/bin:/vagrant/HaLVM/build/sandbox/bin:$PATH \
    cabal --config-file="/vagrant/HaLVM/build/cabal.config" configure
PATH=/vagrant/HaLVM/platform_ghc/bin:/vagrant/HaLVM/build/sandbox/bin:$PATH \
    cabal --config-file="/vagrant/HaLVM/build/cabal.config" build
```

This doesn't work:

```
PATH=/vagrant/HaLVM/platform_ghc/bin:/vagrant/HaLVM/build/sandbox/bin:$PATH \
    cabal --config-file="/vagrant/HaLVM/build/cabal.config" install
```

Note:

```
PATH=/vagrant/HaLVM/platform_ghc/bin:/vagrant/HaLVM/build/sandbox/bin:$PATH \
    cabal --config-file="/vagrant/HaLVM/build/cabal.config" -V
cabal-install version 1.22.3.0
using version 1.22.3.0 of the Cabal library 
```

**Comment by gracjan** [comment]
This change helps:

```
diff --git a/Makefile b/Makefile
index a39bc25..1d20762 100644
--- a/Makefile
+++ b/Makefile
@@ -122,7 +122,9 @@ $1_BIN := $$(BUILDBOX)/bin/$2
 $$($1_BIN): $$(PLATCABAL) | $$($1_SRC)
        $$(BUILDENV) && cd $$($1_SRC) && \
                $$(CABAL) sandbox init --sandbox $$(BUILDBOX) && \
-               $$(CABAL) install
+               $$(CABAL) configure && \
+               $$(CABAL) build && \
+               $$(CABAL) copy
 endef
```

I'm not sure if it does what it is supposed to do.

**Comment by thumphries** [comment]
Hey, maybe that is a workaround for #53! I will test that diff on an Ubuntu VM and get back to you. Did you get a working HaLVM? Were you able to compile some of the examples, like LoopThreads?

**Comment by gracjan** [comment]
Well... you need ANY `happy` installed anyway.

Also the diff should be:

```
diff --git a/Makefile b/Makefile
index a39bc25..1d20762 100644
--- a/Makefile
+++ b/Makefile
@@ -122,7 +122,9 @@ $1_BIN := $$(BUILDBOX)/bin/$2
 $$($1_BIN): $$(PLATCABAL) | $$($1_SRC)
        $$(BUILDENV) && cd $$($1_SRC) && \
                $$(CABAL) sandbox init --sandbox $$(BUILDBOX) && \
-               $$(CABAL) install
+               $$(CABAL) install -only-dep && \
+               $$(CABAL) configure && \
+               $$(CABAL) build && \
+               $$(CABAL) copy
 endef
```

It takes forever to build this and my computer hung due to heat. So I do not know yet how this story finishes.

**Comment by gracjan** [comment]
So I managed to compile `LoopThreads`. It is an ELF.  How do I actually run the thing?

I see that `Makefile` has some commands to run it. But then my host is Mac OS X, HaLVM is build inside Vagrant that has Ubuntu 12.04 in it. Now I need a xen running somehow somewhere.

**Comment by thumphries** [comment]
Heh, looks like that patch does work around the sandbox bug. Would you like to make a PR, or should I?

**Comment by thumphries** [comment]
You've compiled a kernel! Run it on Xen. You'll need a Linux machine.

**Comment by gracjan** [comment]
I needed to install a `happy`, would be good to not require it at all.

**Comment by acw** [comment]
Yes, Xen is required. You can get it to work under Virtual Box or VMWare Fusion on OS/X. The only trick with it is to select "Other 64-bit OS" when building the VM, instead of (for example), Fedora.

**Comment by gracjan** [comment]
I have VirtualBox. I have downloaded Xen thing from http://blogs.citrix.com/2011/01/23/xenserver-in-virtualbox/. Then running it results in:

![screenshot](https://cloud.githubusercontent.com/assets/917978/8014047/a7d9b4dc-0bcd-11e5-9341-b6868cf3eb4a.png)
