### ISSUE TITLE
Successful make followed by make recompiles a lot and fails

### ISSUE THREAD

**Issue by gracjan** [GaloisInc/HaLVM#56]
I would expect successful `make` followed by `make` do nothing but checking that everything is up to date.

**Comment by gracjan** [comment]
Actually it fails with:

```
compiler/utils/Binary.hs:71:1:
    Bad interface file: compiler/stage1/build/Fingerprint.hi
        Something is amiss; requested module  ghc-7.8.3.20150605:Fingerprint differs from name found in the interface file ghc-7.8.3.20150604:Fingerprint
```

**Comment by thumphries** [comment]
This duplicates #15. Would be nice to see PRs for this.

Besides prepping and providing happy / alex / etc, the Makefile just copies / links HaLVM components into the right spots in a GHC subtree, then calls make in halvm-ghc. If you can find any targets in the Makefile that are too liberal, replacing them with actual witnesses of a successful build would be the way to proceed.

**Comment by izgzhen** [comment]
@gracjan I met with this problem too, and i figured out a rather hack solution: emacs into `compiler/stage1/build/Fingerprint.hi` and search for the previous build date, in your example, `0605`, then change it to today.

I am still researching into an elegant way of doing development without rebuilding a lot of stuff, so please mind that it is possibly a bad solution.

**Comment by thumphries** [comment]
Hm, so the build fails if you try to run `make` after the date changes! Nice catch.

The `$(TOPDIR)/halvm-ghc/mk/config.mk` target will fire if you update HALVMCore or XenDevice... and then force the rebuild of `ghc-stage1`, when we really just want the libraries rebuilt.

A quick way to rebuild HALVMCore and XenDevice would be wonderful.
