### ISSUE TITLE
make doesn't produce halvm-ghc executable

### ISSUE THREAD

**Issue by gracjan** [GaloisInc/HaLVM#57]
Running `make` stops at:

```
===--- building final phase
/usr/bin/make -r --no-print-directory -f ghc.mk phase=final rts/dist/build/libHSrts_p.a
utils/ghc-pkg/ghc.mk:46: warning: overriding commands for target `install_utils/ghc-pkg_dist_wrapper'
utils/ghc-pkg/ghc.mk:37: warning: ignoring old commands for target `install_utils/ghc-pkg_dist_wrapper'
make[1]: Leaving directory `/vagrant/HaLVM/halvm-ghc'
/usr/bin/gcc -c -o /vagrant/HaLVM/src/misc/ghci_runtime.o /vagrant/HaLVM/src/misc/ghci_runtime.c
/usr/bin/ar cr /vagrant/HaLVM/halvm-ghc/libminlibc.a (loads of .o files listed)
```

Expected `halvm-ghc` is nowhere to be found...

**Comment by thumphries** [comment]
halvm-ghc is a shell script, and it's copied into place by `make install`.

https://github.com/GaloisInc/HaLVM/blob/master/Makefile#L437

**Comment by gracjan** [comment]
That was surprising :)

**Comment by thumphries** [comment]
There is probably a better way to do it!

**Comment by acw** [comment]
It mostly has to do with the HaLVM needing a custom linker script for final-stage linking. Maybe someday GHC will have a way to build information like this in on a target-specific basis, but for now a wrapper script was easier. See also [halvm-ghc.in](../blob/master/src/scripts/halvm-ghc.in).
