### ISSUE TITLE
halvm-cabal + sandboxes?

### ISSUE THREAD

**Issue by mwotton** [GaloisInc/HaLVM#63]
Does this functionality work? It seems ok when I individually install dependencies, but when I tried putting them in a cabal file and calling halvm-cabal install --only-dependencies, they don't seem visible.

**Comment by acw** [comment]
I honestly have no idea, and my testing environment is broken for development reasons. There shouldn't be any problem, notionally, but I suspect you know the value of "shouldn't be" by now.

I will look into this more when my development systems become more stable again in the near future.

**Comment by acw** [comment]
I have word from one of my colleagues that we're currently using sandboxes on one of our HaLVM projects. So ... I guess it works sometimes. I'll continue to try to reproduce your problem over the next day or so.

**Comment by acw** [comment]
OK, I've been using halvm-cabal sandbox on a bunch of repos without a problem. Do you have an example that doesn't work for you that I could check against?

(Note: I'm using HaLVM's master, not the RPM revision, which I will try to update soon.)

**Comment by dysinger** [comment]
I can't even get base installed without an error (sandbox or not) on a cabal project. Opening a new issue.

**Comment by dysinger** [comment]
ok this ticket can be closed.  It works.  Try it in docker.

```
cat >Dockerfile <<\EOF
FROM fedora:23
RUN dnf -y install autoconf automake bzip2 curl gcc git libtool make patch which
RUN dnf -y install gmp-devel ncurses-devel openssl-devel xen-devel zlib-devel
RUN git clone --recursive https://github.com/GaloisInc/HaLVM.git /usr/local/src/halvm
WORKDIR /usr/local/src/halvm
RUN autoconf
RUN ./configure --enable-gmp
RUN make
RUN make install
RUN ln -sf /usr/local/bin/halvm-ghc /usr/local/bin/ghc
RUN ln -sf /usr/local/bin/halvm-ghc-pkg /usr/local/bin/ghc-pkg
RUN ln -sf /usr/local/bin/halvm-cabal /usr/local/bin/cabal
WORKDIR /
RUN git clone https://github.com/dysinger/halvm-test /usr/local/src/halvm-test
WORKDIR /usr/local/src/halvm-test
RUN halvm-cabal update
RUN halvm-cabal sandbox init
RUN halvm-cabal install --only-dependencies ;# installs microlens
RUN halvm-cabal configure
RUN halvm-cabal build
RUN halvm-cabal install
EOF

docker build --rm=false -t halvm-test .
```
