### ISSUE TITLE
The current halvm rpm-repo doesn't have repodata

### ISSUE THREAD

**Issue by izgzhen** [GaloisInc/HaLVM#65]
I mean this rpm repository `http://www.galois.com/~awick/halvm-fedora/22/`. It doesn't provide a `repodata` (like the one for 21: `http://www.galois.com/~awick/halvm-fedora/21/x86_64/repodata/`) so it is actually not working on my fedora 22.

**Comment by acw** [comment]
Meep! I needed to regenerate the HaLVM RPMs anyways, so will have this fixed by ~5pm US Pacific.

**Comment by izgzhen** [comment]
@acw Then that's cool. I thought there was something wrong. Good luck.
