### ISSUE TITLE
Build system broken if GHC 7.8.4 installed

### ISSUE THREAD

**Issue by mhuesch** [GaloisInc/HaLVM#70]
It seems we don't build our own GHC if we see a 7.8.4 one, and that causes problems.

**Comment by thumphries** [comment]
You can probably fix this by scrapping the else branch here https://github.com/GaloisInc/HaLVM/blob/master/Makefile#L62

**Comment by mhuesch** [comment]
@thumphries thanks, that looks like the right spot. @acw shall I make the change?

**Comment by acw** [comment]
Sure. Just ditch that whole conditional.
