### ISSUE TITLE
Error: Transaction check error

### ISSUE THREAD

**Issue by yemi** [GaloisInc/HaLVM#75]
Trying to get HaLVM up and running but get a problem:
```
dnf install halvm-xen halvm-xen-devel
```
as described [here](https://github.com/GaloisInc/HaLVM/wiki#how-to-i-get-the-halvm)

Which throws the following error:

```
...
Error: Transaction check error:
  file /usr/lib64/fs/ext2fs-lib/fsimage.so from install of halvm-xen-libs-4.5.3-1.fc23.x86_64 conflicts with file from package xen-libs-4.5.3-8.fc23.x86_64
...
```

I get about 15 of these conflicts.

I havent used Fedora or dnf before, but wanted to use them in order to start contributing to HaLVM, so bear with me if this is an easy dnf fix

**Comment by acw** [comment]
Hi!

Yeah, you can't have both the halvm-xen packages and the xen packages on the same machine. You'll need to 'dnf erase xen' as a first step.

**Comment by yemi** [comment]
```
sudo dnf erase xen
No match for argument: xen
Error: No packages marked for removal.
```

**Comment by TomMD** [comment]
@yemi 

The message said `conflicts with file from package xen-libs...`

So perhaps `sudo dnf erase xen-libs`.

**Comment by yemi** [comment]
That did the trick!
