### ISSUE TITLE
Add support for proper GMP detection in the HaLVM autoconf file

### ISSUE THREAD

**Issue by acw** [GaloisInc/HaLVM#76]
I'm honestly not 100% sure what this means, but I'm cleaning out an old notes file and saw this. Might have already been done.

**Comment by erikd** [comment]
I would say that https://github.com/GaloisInc/HaLVM/blob/master/configure.ac#L149 is at least part way to answering this.

**Comment by dysinger** [comment]
what would be the test to close this ticket? example: it works on the following:
- centos
- fedora
- debian
- ubuntu

they all have varying versions of gmp

**Comment by acw** [comment]
If that works, then we're probably good.

Actually, has this been tested when one has one of the dynamic and static libraries installed, but not both?
