### ISSUE TITLE
HACKING.md

### ISSUE THREAD

**Issue by izgzhen** [GaloisInc/HaLVM#81]
I found that currently there are three sources including instructions of building a development environment:

- https://github.com/GaloisInc/HaLVM/wiki
- https://github.com/GaloisInc/HaLVM/wiki/Building-a-Development-Virtual-Machine
- https://github.com/GaloisInc/HaLVM/blob/master/README.md

There are some overlapping, contradiction, and possibly outdated info.

I am currently redeploying the newest things so maybe I can help organize a *canonical* `HACKING.md` under this repo's source root. (Why not wiki? Maybe putting it here is easier to track and many people might expect this thing as well.)

NOTE: I am kinda lured to do something with HaLVM after seeing its v3 plan, but it is purely amateur work :)

**Comment by acw** [comment]
That would be great. Would totally love to see this. 👍
