### ISSUE TITLE
Can I run a HALVM unikernel from the Linux command line?

### ISSUE THREAD

**Issue by crowdwave** [GaloisInc/HaLVM#84]
I'd like to run a simple HALVM web server just from the Linux command line. Is this possible?

thanks

**Comment by acw** [comment]
For the moment, no. HaLVMs only run on Xen. (You do control Xen from the Linux command line, though. So maybe I mean yes?)

It is a goal of our next major revision of the HaLVM for it to be easily retargetable between a variety of platforms, including Linux.
