### ISSUE TITLE
distributed-process

### ISSUE THREAD

**Issue by johnpmayer** [GaloisInc/HaLVM#9]
For the next release, would it be possible to try and support the dependencies for Cloud Haskell, distributed-process?

http://hackage.haskell.org/package/distributed-process-0.2.0

I'd very much like to try to write backends on top of IVC or HaNS

**Comment by dysinger** [comment]
Is this a direct HaLVM concern? If so lets list the action items. IMHO if base libraries supported, there should be no reason distributed-process wouldn't just layer in.

**Comment by acw** [comment]
Given that the original reporter never posted a test case, I think we should close it.

**Comment by dysinger** [comment]
btw @acw @johnpmayer @TomMD @elliottt 

```
$ cat >Dockerfile<<\EOF
FROM fedora:23
RUN dnf -y install autoconf automake bzip2 curl gcc git libtool make patch which
RUN dnf -y install gmp-devel ncurses-devel openssl-devel xen-devel zlib-devel
RUN git clone --recursive https://github.com/GaloisInc/HaLVM.git /usr/local/src/halvm
WORKDIR /usr/local/src/halvm
RUN autoconf
RUN ./configure --enable-gmp
RUN make
RUN make install
RUN halvm-cabal update
RUN halvm-cabal install --global distributed-process
EOF

$ docker build -t distribute-process-halvm .
...
Successfully built e33854cdfab2
```

**Comment by TomMD** [comment]
@dysinger That's perfect.  Thanks for the CC, I love it.
