### ISSUE TITLE
Ditch `platform-ghc`, instead require correct software to be installed

### ISSUE THREAD

**Issue by acw** [GaloisInc/HaLVM#94]
Like it says up top.

We spend a lot of time building a bunch of compiler tools that we'll later use to build the HaLVM. This was done for historical reasons that no longer apply, and create an unnecessarily complicated build system that doesn't clean/rebuild well. We should strongly investigate how to best remove this system by forcing the required infrastructure to exist on the build system via configure scripts.

This will have one serious downside for developers, in that it will force them into somewhat constrained package requirements. But on the upside, it will dramatically improve the build speed of the whole system.

**Comment by erikd** [comment]
I would be nice to be able to do this without stack. For most of my own projects I just use cabal with a per-project sandbox and at work I use [mafia](https://github.com/ambiata/mafia) which is a cabal wrapper which basically solves all the same problems as stack (but in a slightly different way).

**Comment by acw** [comment]
I'm also a sandbox fan, albeit one really excited about new-build. Hence my desire to stick with that toolset as much as possible. Also, Fedora 24, at least, didn't come with an stack package.On Dec 30, 2016 1:46 PM, Erik de Castro Lopo <notifications@github.com> wrote:I would be nice to be able to do this without stack. For most of my own projects I just use cabal with a per-project sandbox and at work I use mafia which is a cabal wrapper which basically solves all the same problems as stack (but in a slightly different way).

**Comment by acw** [comment]
I think this is now done. Yay!
